/*
 * Generated by XDoclet - Do not edit!
 */
package examples;

/**
 * Remote interface for CalculatorBean.
 */
public interface CalculatorBean
   extends javax.ejb.EJBObject
{
   /**
    * The method that returns the multiplied value
    */
   public int multiply( int val1,int val2 )
      throws java.rmi.RemoteException;

}
