/*
 * Generated by XDoclet - Do not edit!
 */
package examples;

/**
 * Home interface for CalculatorBean.
 */
public interface CalculatorBeanHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/CalculatorBean";
   public static final String JNDI_NAME="CalculatorSessionBean";

   public examples.CalculatorBean create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
