/*
 * Generated by XDoclet - Do not edit!
 */
package examples;

/**
 * Remote interface for ShoppingCart.
 */
public interface ShoppingCart
   extends javax.ejb.EJBObject
{
   /**
    * The method that adds the item
    */
   public void addItem( java.lang.String name )
      throws java.rmi.RemoteException;

   /**
    * The method that removes the item
    */
   public void removeItem( java.lang.String name )
      throws java.rmi.RemoteException;

   /**
    * The method that set the item name
    */
   public void setItem( java.lang.String name )
      throws java.rmi.RemoteException;

   /**
    * The method that sets the submit action
    */
   public void setSubmit( java.lang.String s )
      throws java.rmi.RemoteException;

   /**
    * The method that returns the all the items in the cart
    */
   public java.lang.String[] getItems(  )
      throws java.rmi.RemoteException;

}
