/*
 * Generated by XDoclet - Do not edit!
 */
package examples;

/**
 * Home interface for ShoppingCart.
 */
public interface ShoppingCartHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/ShoppingCart";
   public static final String JNDI_NAME="ShoppingCart";

   public examples.ShoppingCart create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
