/*
 * Generated by XDoclet - Do not edit!
 */
package examples;

/**
 * Local home interface for TestSessionBean.
 */
public interface TestSessionBeanLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/TestSessionBeanLocal";
   public static final String JNDI_NAME="TestSessionBeanLocal";

   public examples.TestSessionBeanLocal create()
      throws javax.ejb.CreateException;

}
